/**
 * Application Constants & Enums
 */

const TASK_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const APPLICATION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
};

const ASSIGNED_TASK_STATUS = {
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const USER_ROLES = {
  POSTER: 'POSTER',
  TASKER: 'TASKER',
  MANAGER: 'MANAGER',
  ADMIN: 'ADMIN',
};

const ASSIGNED_BY = {
  MANUAL: 'MANUAL',
  AUTO_MATCH: 'AUTO_MATCH',
};

const TASK_TYPES = {
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
};

const LOCATION_TYPES = {
  TASK_LOCATION: 'TASK_LOCATION',
  MEETING_POINT: 'MEETING_POINT',
};

// Matching algorithm weights
const MATCHING_WEIGHTS = {
  PRICE: 0.30,
  RATING: 0.25,
  DISTANCE: 0.20,
  COMPLETION_RATE: 0.15,
  RESPONSE_TIME: 0.10,
};

// Pagination defaults
const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 50,
};

module.exports = {
  TASK_STATUS,
  APPLICATION_STATUS,
  ASSIGNED_TASK_STATUS,
  USER_ROLES,
  ASSIGNED_BY,
  TASK_TYPES,
  LOCATION_TYPES,
  MATCHING_WEIGHTS,
  PAGINATION,
};
