import { MaterialCommunityIcons } from '@expo/vector-icons';

export interface JobSubcategory {
  id: string;
  name: string;
  slug: string;
  apiCategoryId: string;
}

export interface JobField {
  id: string;
  name: string;
  slug: string;
  icon: keyof typeof MaterialCommunityIcons.glyphMap;
  isHot?: boolean;
  apiCategoryId: string;
  subcategories: JobSubcategory[];
}

export const JOB_FIELDS: JobField[] = [
  {
    id: 'field-writing',
    name: 'Nội dung & Viết lách',
    slug: 'writing',
    icon: 'text-box-edit-outline',
    isHot: true,
    apiCategoryId: 'content',
    subcategories: [
      { id: 'sub-writing-1', name: 'Viết caption mạng xã hội', slug: 'social-caption', apiCategoryId: 'content' },
      { id: 'sub-writing-2', name: 'Viết bài blog', slug: 'blog-post', apiCategoryId: 'content' },
      { id: 'sub-writing-3', name: 'Viết bài chuẩn SEO', slug: 'seo-post', apiCategoryId: 'content' },
      { id: 'sub-writing-4', name: 'Viết nội dung website', slug: 'website-content', apiCategoryId: 'content' },
      { id: 'sub-writing-5', name: 'Viết mô tả sản phẩm', slug: 'product-desc', apiCategoryId: 'content' },
      { id: 'sub-writing-6', name: 'Viết nội dung quảng cáo', slug: 'ads-copy', apiCategoryId: 'content' },
      { id: 'sub-writing-7', name: 'Viết kịch bản TikTok', slug: 'tiktok-script', apiCategoryId: 'content' },
      { id: 'sub-writing-8', name: 'Viết kịch bản YouTube', slug: 'youtube-script', apiCategoryId: 'content' },
      { id: 'sub-writing-9', name: 'Viết email marketing', slug: 'email-copy', apiCategoryId: 'content' },
      { id: 'sub-writing-10', name: 'Viết CV và thư xin việc', slug: 'cv-coverletter', apiCategoryId: 'content' },
      { id: 'sub-writing-11', name: 'Biên tập nội dung', slug: 'content-editing', apiCategoryId: 'content' },
      { id: 'sub-writing-12', name: 'Kiểm tra chính tả', slug: 'spell-check', apiCategoryId: 'content' },
      { id: 'sub-writing-13', name: 'Viết lại nội dung', slug: 'rewrite', apiCategoryId: 'content' },
      { id: 'sub-writing-14', name: 'Tóm tắt tài liệu', slug: 'doc-summary', apiCategoryId: 'content' },
    ],
  },
  {
    id: 'field-design',
    name: 'Thiết kế',
    slug: 'design',
    icon: 'palette-outline',
    isHot: true,
    apiCategoryId: 'design',
    subcategories: [
      { id: 'sub-design-1', name: 'Thiết kế logo', slug: 'logo-design', apiCategoryId: 'design' },
      { id: 'sub-design-2', name: 'Thiết kế banner', slug: 'banner-design', apiCategoryId: 'design' },
      { id: 'sub-design-3', name: 'Thiết kế poster', slug: 'poster-design', apiCategoryId: 'design' },
      { id: 'sub-design-4', name: 'Thiết kế bài đăng mạng xã hội', slug: 'social-post-design', apiCategoryId: 'design' },
      { id: 'sub-design-5', name: 'Thiết kế thumbnail', slug: 'thumbnail-design', apiCategoryId: 'design' },
      { id: 'sub-design-6', name: 'Thiết kế menu', slug: 'menu-design', apiCategoryId: 'design' },
      { id: 'sub-design-7', name: 'Thiết kế danh thiếp', slug: 'business-card-design', apiCategoryId: 'design' },
      { id: 'sub-design-8', name: 'Thiết kế brochure', slug: 'brochure-design', apiCategoryId: 'design' },
      { id: 'sub-design-9', name: 'Thiết kế slide PowerPoint', slug: 'powerpoint-design', apiCategoryId: 'design' },
      { id: 'sub-design-10', name: 'Thiết kế CV', slug: 'cv-design', apiCategoryId: 'design' },
      { id: 'sub-design-11', name: 'Thiết kế infographic', slug: 'infographic-design', apiCategoryId: 'design' },
      { id: 'sub-design-12', name: 'Thiết kế giao diện mobile', slug: 'mobile-ui-design', apiCategoryId: 'design' },
      { id: 'sub-design-13', name: 'Thiết kế giao diện website', slug: 'web-ui-design', apiCategoryId: 'design' },
      { id: 'sub-design-14', name: 'Chỉnh sửa template Canva', slug: 'canva-edit', apiCategoryId: 'design' },
      { id: 'sub-design-15', name: 'Vẽ icon và minh họa', slug: 'illustration-design', apiCategoryId: 'design' },
    ],
  },
  {
    id: 'field-media',
    name: 'Video, Hình ảnh & Âm thanh',
    slug: 'video-media',
    icon: 'movie-open-edit-outline',
    apiCategoryId: 'design',
    subcategories: [
      { id: 'sub-media-1', name: 'Chỉnh sửa video TikTok', slug: 'tiktok-edit', apiCategoryId: 'design' },
      { id: 'sub-media-2', name: 'Chỉnh sửa video Reels', slug: 'reels-edit', apiCategoryId: 'design' },
      { id: 'sub-media-3', name: 'Chỉnh sửa YouTube Shorts', slug: 'shorts-edit', apiCategoryId: 'design' },
      { id: 'sub-media-4', name: 'Chỉnh sửa video YouTube', slug: 'youtube-edit', apiCategoryId: 'design' },
      { id: 'sub-media-5', name: 'Cắt ghép video', slug: 'video-cutting', apiCategoryId: 'design' },
      { id: 'sub-media-6', name: 'Thêm phụ đề video', slug: 'video-subtitle', apiCategoryId: 'design' },
      { id: 'sub-media-7', name: 'Chỉnh màu video', slug: 'color-grading', apiCategoryId: 'design' },
      { id: 'sub-media-8', name: 'Tách video dài thành video ngắn', slug: 'video-slicing', apiCategoryId: 'design' },
      { id: 'sub-media-9', name: 'Làm intro và outro', slug: 'intro-outro', apiCategoryId: 'design' },
      { id: 'sub-media-10', name: 'Tách nền ảnh', slug: 'bg-remove', apiCategoryId: 'design' },
      { id: 'sub-media-11', name: 'Chỉnh sửa ảnh sản phẩm', slug: 'product-photo-edit', apiCategoryId: 'design' },
      { id: 'sub-media-12', name: 'Retouch ảnh', slug: 'photo-retouch', apiCategoryId: 'design' },
      { id: 'sub-media-13', name: 'Xóa vật thể trong ảnh', slug: 'object-remove', apiCategoryId: 'design' },
      { id: 'sub-media-14', name: 'Thu âm giọng đọc', slug: 'voiceover', apiCategoryId: 'design' },
      { id: 'sub-media-15', name: 'Lọc tạp âm', slug: 'noise-filter', apiCategoryId: 'design' },
      { id: 'sub-media-16', name: 'Chỉnh sửa podcast', slug: 'podcast-edit', apiCategoryId: 'design' },
      { id: 'sub-media-17', name: 'Chuyển audio thành văn bản', slug: 'audio-to-text', apiCategoryId: 'design' },
    ],
  },
  {
    id: 'field-marketing',
    name: 'Marketing',
    slug: 'marketing',
    icon: 'bullhorn-outline',
    isHot: true,
    apiCategoryId: 'others',
    subcategories: [
      { id: 'sub-marketing-1', name: 'Quản lý fanpage', slug: 'fanpage-management', apiCategoryId: 'others' },
      { id: 'sub-marketing-2', name: 'Quản lý kênh TikTok', slug: 'tiktok-management', apiCategoryId: 'others' },
      { id: 'sub-marketing-3', name: 'Lên lịch đăng bài', slug: 'post-scheduling', apiCategoryId: 'others' },
      { id: 'sub-marketing-4', name: 'Lập kế hoạch nội dung', slug: 'content-planning', apiCategoryId: 'others' },
      { id: 'sub-marketing-5', name: 'Tìm ý tưởng nội dung', slug: 'content-ideation', apiCategoryId: 'others' },
      { id: 'sub-marketing-6', name: 'Nghiên cứu từ khóa SEO', slug: 'seo-keyword-research', apiCategoryId: 'others' },
      { id: 'sub-marketing-7', name: 'Tối ưu bài viết SEO', slug: 'seo-optimization', apiCategoryId: 'others' },
      { id: 'sub-marketing-8', name: 'Phân tích đối thủ', slug: 'competitor-analysis', apiCategoryId: 'others' },
      { id: 'sub-marketing-9', name: 'Nghiên cứu hashtag', slug: 'hashtag-research', apiCategoryId: 'others' },
      { id: 'sub-marketing-10', name: 'Tìm kiếm KOC', slug: 'koc-outreach', apiCategoryId: 'others' },
      { id: 'sub-marketing-11', name: 'Tìm kiếm influencer', slug: 'influencer-outreach', apiCategoryId: 'others' },
      { id: 'sub-marketing-12', name: 'Quản lý cộng đồng online', slug: 'community-management', apiCategoryId: 'others' },
      { id: 'sub-marketing-13', name: 'Theo dõi số liệu chiến dịch', slug: 'metrics-tracking', apiCategoryId: 'others' },
      { id: 'sub-marketing-14', name: 'Lập báo cáo marketing', slug: 'marketing-reporting', apiCategoryId: 'others' },
      { id: 'sub-marketing-15', name: 'Hỗ trợ email marketing', slug: 'email-marketing-support', apiCategoryId: 'others' },
      { id: 'sub-marketing-16', name: 'Audit fanpage cơ bản', slug: 'fanpage-audit', apiCategoryId: 'others' },
    ],
  },
  {
    id: 'field-tech',
    name: 'Công nghệ',
    slug: 'tech',
    icon: 'code-tags',
    isHot: true,
    apiCategoryId: 'tech',
    subcategories: [
      { id: 'sub-tech-1', name: 'Thiết kế landing page', slug: 'landing-page-dev', apiCategoryId: 'tech' },
      { id: 'sub-tech-2', name: 'Phát triển website', slug: 'website-dev', apiCategoryId: 'tech' },
      { id: 'sub-tech-3', name: 'Chỉnh sửa giao diện website', slug: 'web-frontend-edit', apiCategoryId: 'tech' },
      { id: 'sub-tech-4', name: 'Sửa lỗi HTML/CSS', slug: 'html-css-debug', apiCategoryId: 'tech' },
      { id: 'sub-tech-5', name: 'Sửa lỗi React', slug: 'react-debug', apiCategoryId: 'tech' },
      { id: 'sub-tech-6', name: 'Sửa lỗi React Native', slug: 'react-native-debug', apiCategoryId: 'tech' },
      { id: 'sub-tech-7', name: 'Sửa lỗi Flutter', slug: 'flutter-debug', apiCategoryId: 'tech' },
      { id: 'sub-tech-8', name: 'Sửa lỗi Java Spring Boot', slug: 'spring-boot-debug', apiCategoryId: 'tech' },
      { id: 'sub-tech-9', name: 'Sửa lỗi Node.js', slug: 'nodejs-debug', apiCategoryId: 'tech' },
      { id: 'sub-tech-10', name: 'Kết nối API', slug: 'api-integration', apiCategoryId: 'tech' },
      { id: 'sub-tech-11', name: 'Tạo tính năng mobile', slug: 'mobile-feature-dev', apiCategoryId: 'tech' },
      { id: 'sub-tech-12', name: 'Tạo tính năng website', slug: 'web-feature-dev', apiCategoryId: 'tech' },
      { id: 'sub-tech-13', name: 'Cài đặt WordPress', slug: 'wordpress-install', apiCategoryId: 'tech' },
      { id: 'sub-tech-14', name: 'Chỉnh sửa WordPress', slug: 'wordpress-edit', apiCategoryId: 'tech' },
      { id: 'sub-tech-15', name: 'Viết truy vấn SQL', slug: 'sql-queries', apiCategoryId: 'tech' },
      { id: 'sub-tech-16', name: 'Sửa lỗi database', slug: 'db-debug', apiCategoryId: 'tech' },
      { id: 'sub-tech-17', name: 'Kiểm thử website', slug: 'web-testing', apiCategoryId: 'tech' },
      { id: 'sub-tech-18', name: 'Kiểm thử ứng dụng', slug: 'app-testing', apiCategoryId: 'tech' },
      { id: 'sub-tech-19', name: 'Viết test case', slug: 'test-case-writing', apiCategoryId: 'tech' },
      { id: 'sub-tech-20', name: 'Deploy website', slug: 'web-deployment', apiCategoryId: 'tech' },
      { id: 'sub-tech-21', name: 'Cấu hình hosting và domain', slug: 'hosting-domain-config', apiCategoryId: 'tech' },
    ],
  },
  {
    id: 'field-admin',
    name: 'Nhập liệu & Hành chính',
    slug: 'admin',
    icon: 'database-edit-outline',
    apiCategoryId: 'others',
    subcategories: [
      { id: 'sub-admin-1', name: 'Nhập dữ liệu Excel', slug: 'excel-entry', apiCategoryId: 'others' },
      { id: 'sub-admin-2', name: 'Nhập thông tin sản phẩm', slug: 'product-entry', apiCategoryId: 'others' },
      { id: 'sub-admin-3', name: 'Nhập danh sách khách hàng', slug: 'customer-data-entry', apiCategoryId: 'others' },
      { id: 'sub-admin-4', name: 'Đánh máy tài liệu', slug: 'document-typing', apiCategoryId: 'others' },
      { id: 'sub-admin-5', name: 'Chuyển PDF sang Word', slug: 'pdf-to-word', apiCategoryId: 'others' },
      { id: 'sub-admin-6', name: 'Chuyển PDF sang Excel', slug: 'pdf-to-excel', apiCategoryId: 'others' },
      { id: 'sub-admin-7', name: 'Chuyển hình ảnh thành văn bản', slug: 'image-to-text', apiCategoryId: 'others' },
      { id: 'sub-admin-8', name: 'Làm sạch dữ liệu', slug: 'data-cleaning', apiCategoryId: 'others' },
      { id: 'sub-admin-9', name: 'Xóa dữ liệu trùng lặp', slug: 'duplicate-remove', apiCategoryId: 'others' },
      { id: 'sub-admin-10', name: 'Phân loại dữ liệu', slug: 'data-classification', apiCategoryId: 'others' },
      { id: 'sub-admin-11', name: 'Gộp file Excel', slug: 'excel-merge', apiCategoryId: 'others' },
      { id: 'sub-admin-12', name: 'Tạo bảng tính', slug: 'spreadsheet-creation', apiCategoryId: 'others' },
      { id: 'sub-admin-13', name: 'Tạo Google Forms', slug: 'google-forms-setup', apiCategoryId: 'others' },
      { id: 'sub-admin-14', name: 'Tổng hợp kết quả khảo sát', slug: 'survey-aggregation', apiCategoryId: 'others' },
      { id: 'sub-admin-15', name: 'Sắp xếp tài liệu', slug: 'file-organization', apiCategoryId: 'others' },
      { id: 'sub-admin-16', name: 'Đổi tên file hàng loạt', slug: 'batch-file-rename', apiCategoryId: 'others' },
      { id: 'sub-admin-17', name: 'Sắp xếp Google Drive', slug: 'google-drive-organization', apiCategoryId: 'others' },
      { id: 'sub-admin-18', name: 'Quản lý lịch hẹn', slug: 'calendar-management', apiCategoryId: 'others' },
      { id: 'sub-admin-19', name: 'Chuẩn bị biên bản cuộc họp', slug: 'meeting-minutes', apiCategoryId: 'others' },
      { id: 'sub-admin-20', name: 'Trợ lý ảo online', slug: 'virtual-assistant', apiCategoryId: 'others' },
    ],
  },
  {
    id: 'field-research',
    name: 'Nghiên cứu',
    slug: 'research',
    icon: 'file-search-outline',
    apiCategoryId: 'research',
    subcategories: [
      { id: 'sub-research-1', name: 'Nghiên cứu thị trường', slug: 'market-research', apiCategoryId: 'research' },
      { id: 'sub-research-2', name: 'Nghiên cứu đối thủ', slug: 'competitor-research', apiCategoryId: 'research' },
      { id: 'sub-research-3', name: 'Nghiên cứu khách hàng', slug: 'customer-research', apiCategoryId: 'research' },
      { id: 'sub-research-4', name: 'Nghiên cứu sản phẩm', slug: 'product-research', apiCategoryId: 'research' },
      { id: 'sub-research-5', name: 'Nghiên cứu giá bán', slug: 'pricing-research', apiCategoryId: 'research' },
      { id: 'sub-research-6', name: 'Tìm nhà cung cấp', slug: 'supplier-sourcing', apiCategoryId: 'research' },
      { id: 'sub-research-7', name: 'Tìm xưởng sản xuất', slug: 'factory-sourcing', apiCategoryId: 'research' },
      { id: 'sub-research-8', name: 'Tìm thông tin doanh nghiệp', slug: 'business-info-search', apiCategoryId: 'research' },
      { id: 'sub-research-9', name: 'Tìm danh sách khách hàng tiềm năng', slug: 'lead-generation-sourcing', apiCategoryId: 'research' },
      { id: 'sub-research-10', name: 'Tìm nguồn tài liệu', slug: 'literature-search', apiCategoryId: 'research' },
      { id: 'sub-research-11', name: 'Tìm bài nghiên cứu', slug: 'research-papers-search', apiCategoryId: 'research' },
      { id: 'sub-research-12', name: 'Tóm tắt báo cáo', slug: 'report-summary', apiCategoryId: 'research' },
      { id: 'sub-research-13', name: 'Tổng hợp dữ liệu Internet', slug: 'web-data-synthesis', apiCategoryId: 'research' },
      { id: 'sub-research-14', name: 'Nghiên cứu xu hướng TikTok', slug: 'tiktok-trend-research', apiCategoryId: 'research' },
      { id: 'sub-research-15', name: 'Nghiên cứu xu hướng nội dung', slug: 'content-trend-research', apiCategoryId: 'research' },
      { id: 'sub-research-16', name: 'Nghiên cứu từ khóa', slug: 'keyword-trend-research', apiCategoryId: 'research' },
      { id: 'sub-research-17', name: 'Thiết kế khảo sát', slug: 'survey-design', apiCategoryId: 'research' },
      { id: 'sub-research-18', name: 'Tổng hợp kết quả khảo sát', slug: 'survey-results-synthesis', apiCategoryId: 'research' },
      { id: 'sub-research-19', name: 'Kiểm chứng thông tin', slug: 'fact-checking', apiCategoryId: 'research' },
    ],
  },
  {
    id: 'field-ecommerce',
    name: 'Thương mại điện tử',
    slug: 'ecommerce',
    icon: 'shopping-outline',
    apiCategoryId: 'others',
    subcategories: [
      { id: 'sub-ecommerce-1', name: 'Đăng sản phẩm lên Shopee', slug: 'shopee-listing', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-2', name: 'Đăng sản phẩm lên TikTok Shop', slug: 'tiktok-shop-listing', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-3', name: 'Đăng sản phẩm lên Lazada', slug: 'lazada-listing', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-4', name: 'Đăng sản phẩm lên website', slug: 'website-listing', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-5', name: 'Viết tiêu đề sản phẩm', slug: 'product-title-writing', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-6', name: 'Viết mô tả sản phẩm', slug: 'product-desc-writing', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-7', name: 'Chỉnh sửa ảnh sản phẩm', slug: 'product-photo-ecommerce', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-8', name: 'Phân loại sản phẩm', slug: 'product-categorization', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-9', name: 'Tạo mã SKU', slug: 'sku-generation', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-10', name: 'Cập nhật giá sản phẩm', slug: 'price-update', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-11', name: 'Cập nhật tồn kho', slug: 'inventory-update', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-12', name: 'Quản lý gian hàng', slug: 'store-management', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-13', name: 'Theo dõi đơn hàng', slug: 'order-tracking', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-14', name: 'Xác nhận đơn hàng', slug: 'order-confirmation', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-15', name: 'Trả lời tin nhắn khách hàng', slug: 'chat-support-ecommerce', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-16', name: 'Tư vấn sản phẩm', slug: 'product-consultation', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-17', name: 'Hỗ trợ chốt đơn', slug: 'sales-closing-support', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-18', name: 'Viết kịch bản livestream', slug: 'livestream-script', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-19', name: 'Trực bình luận livestream', slug: 'livestream-comment-moderation', apiCategoryId: 'others' },
      { id: 'sub-ecommerce-20', name: 'Nghiên cứu sản phẩm bán chạy', slug: 'hot-product-research', apiCategoryId: 'others' },
    ],
  },
  {
    id: 'field-translation',
    name: 'Dịch thuật & Ngôn ngữ',
    slug: 'translation',
    icon: 'translate',
    apiCategoryId: 'content',
    subcategories: [
      { id: 'sub-translation-1', name: 'Dịch Anh sang Việt', slug: 'en-to-vi-trans', apiCategoryId: 'content' },
      { id: 'sub-translation-2', name: 'Dịch Việt sang Anh', slug: 'vi-to-en-trans', apiCategoryId: 'content' },
      { id: 'sub-translation-3', name: 'Dịch tài liệu', slug: 'doc-translation', apiCategoryId: 'content' },
      { id: 'sub-translation-4', name: 'Dịch bài viết', slug: 'article-translation', apiCategoryId: 'content' },
      { id: 'sub-translation-5', name: 'Dịch nội dung website', slug: 'web-translation', apiCategoryId: 'content' },
      { id: 'sub-translation-6', name: 'Dịch mô tả sản phẩm', slug: 'product-translation', apiCategoryId: 'content' },
      { id: 'sub-translation-7', name: 'Dịch email', slug: 'email-translation', apiCategoryId: 'content' },
      { id: 'sub-translation-8', name: 'Dịch phụ đề video', slug: 'subtitle-translation', apiCategoryId: 'content' },
      { id: 'sub-translation-9', name: 'Dịch tài liệu kỹ thuật', slug: 'technical-translation', apiCategoryId: 'content' },
      { id: 'sub-translation-10', name: 'Kiểm tra bản dịch', slug: 'proofreading-translation', apiCategoryId: 'content' },
      { id: 'sub-translation-11', name: 'Sửa ngữ pháp tiếng Anh', slug: 'grammar-check-en', apiCategoryId: 'content' },
      { id: 'sub-translation-12', name: 'Biên tập văn bản tiếng Anh', slug: 'editing-en', apiCategoryId: 'content' },
      { id: 'sub-translation-13', name: 'Chuyển audio thành văn bản', slug: 'audio-to-text-language', apiCategoryId: 'content' },
      { id: 'sub-translation-14', name: 'Chuyển video thành văn bản', slug: 'video-to-text-language', apiCategoryId: 'content' },
      { id: 'sub-translation-15', name: 'Thu âm tiếng Anh', slug: 'voiceover-en', apiCategoryId: 'content' },
      { id: 'sub-translation-16', name: 'Luyện phát âm', slug: 'pronunciation-training', apiCategoryId: 'content' },
      { id: 'sub-translation-17', name: 'Luyện giao tiếp online', slug: 'speaking-practice-online', apiCategoryId: 'content' },
    ],
  },
  {
    id: 'field-study',
    name: 'Hỗ trợ học tập',
    slug: 'study',
    icon: 'school-outline',
    apiCategoryId: 'study',
    subcategories: [
      { id: 'sub-study-1', name: 'Gia sư Toán online', slug: 'math-tutor-online', apiCategoryId: 'study' },
      { id: 'sub-study-2', name: 'Gia sư tiếng Anh online', slug: 'english-tutor-online', apiCategoryId: 'study' },
      { id: 'sub-study-3', name: 'Gia sư Tin học online', slug: 'cs-tutor-online', apiCategoryId: 'study' },
      { id: 'sub-study-4', name: 'Gia sư môn phổ thông', slug: 'school-subject-tutor', apiCategoryId: 'study' },
      { id: 'sub-study-5', name: 'Hướng dẫn lập trình', slug: 'programming-guidance', apiCategoryId: 'study' },
      { id: 'sub-study-6', name: 'Hướng dẫn làm bài tập', slug: 'homework-guidance', apiCategoryId: 'study' },
      { id: 'sub-study-7', name: 'Giải thích đề bài', slug: 'problem-explanation', apiCategoryId: 'study' },
      { id: 'sub-study-8', name: 'Review bài làm', slug: 'homework-review', apiCategoryId: 'study' },
      { id: 'sub-study-9', name: 'Sửa bài viết', slug: 'essay-revision', apiCategoryId: 'study' },
      { id: 'sub-study-10', name: 'Tìm tài liệu học tập', slug: 'study-docs-sourcing', apiCategoryId: 'study' },
      { id: 'sub-study-11', name: 'Hướng dẫn nghiên cứu', slug: 'research-guidance', apiCategoryId: 'study' },
      { id: 'sub-study-12', name: 'Hướng dẫn trích dẫn tài liệu', slug: 'citation-guidance', apiCategoryId: 'study' },
      { id: 'sub-study-13', name: 'Định dạng báo cáo', slug: 'report-formatting', apiCategoryId: 'study' },
      { id: 'sub-study-14', name: 'Thiết kế slide thuyết trình', slug: 'presentation-design-study', apiCategoryId: 'study' },
      { id: 'sub-study-15', name: 'Luyện thuyết trình', slug: 'presentation-coaching', apiCategoryId: 'study' },
      { id: 'sub-study-16', name: 'Hướng dẫn Word', slug: 'ms-word-tutorial', apiCategoryId: 'study' },
      { id: 'sub-study-17', name: 'Hướng dẫn Excel', slug: 'ms-excel-tutorial', apiCategoryId: 'study' },
      { id: 'sub-study-18', name: 'Hướng dẫn PowerPoint', slug: 'ms-powerpoint-tutorial', apiCategoryId: 'study' },
      { id: 'sub-study-19', name: 'Hướng dẫn Canva', slug: 'canva-tutorial', apiCategoryId: 'study' },
      { id: 'sub-study-20', name: 'Review CV', slug: 'cv-review', apiCategoryId: 'study' },
      { id: 'sub-study-21', name: 'Luyện phỏng vấn', slug: 'interview-practice', apiCategoryId: 'study' },
    ],
  },
  {
    id: 'field-customer',
    name: 'Chăm sóc khách hàng',
    slug: 'customer-service',
    icon: 'headset',
    apiCategoryId: 'others',
    subcategories: [
      { id: 'sub-customer-1', name: 'Trực tin nhắn fanpage', slug: 'fanpage-chat-support', apiCategoryId: 'others' },
      { id: 'sub-customer-2', name: 'Trả lời bình luận', slug: 'comment-moderation', apiCategoryId: 'others' },
      { id: 'sub-customer-3', name: 'Trả lời live chat', slug: 'live-chat-support', apiCategoryId: 'others' },
      { id: 'sub-customer-4', name: 'Tư vấn khách hàng online', slug: 'customer-consultation', apiCategoryId: 'others' },
      { id: 'sub-customer-5', name: 'Hỗ trợ khách sử dụng sản phẩm', slug: 'product-usage-support', apiCategoryId: 'others' },
      { id: 'sub-customer-6', name: 'Gọi xác nhận đơn hàng', slug: 'order-confirm-call', apiCategoryId: 'others' },
      { id: 'sub-customer-7', name: 'Nhắc khách thanh toán', slug: 'payment-reminder-call', apiCategoryId: 'others' },
      { id: 'sub-customer-8', name: 'Xác nhận lịch hẹn', slug: 'appointment-confirmation-call', apiCategoryId: 'others' },
      { id: 'sub-customer-9', name: 'Nhắc lịch hẹn', slug: 'appointment-reminder-call', apiCategoryId: 'others' },
      { id: 'sub-customer-10', name: 'Tiếp nhận phản hồi', slug: 'feedback-reception', apiCategoryId: 'others' },
      { id: 'sub-customer-11', name: 'Tiếp nhận khiếu nại', slug: 'complaint-reception', apiCategoryId: 'others' },
      { id: 'sub-customer-12', name: 'Tổng hợp vấn đề khách hàng', slug: 'customer-issue-summary', apiCategoryId: 'others' },
      { id: 'sub-customer-13', name: 'Chăm sóc khách hàng sau mua', slug: 'post-purchase-care', apiCategoryId: 'others' },
      { id: 'sub-customer-14', name: 'Gọi khảo sát khách hàng', slug: 'feedback-survey-call', apiCategoryId: 'others' },
      { id: 'sub-customer-15', name: 'Quản lý cộng đồng', slug: 'community-moderation', apiCategoryId: 'others' },
      { id: 'sub-customer-16', name: 'Duyệt bài trong nhóm', slug: 'group-post-approval', apiCategoryId: 'others' },
      { id: 'sub-customer-17', name: 'Kiểm soát bình luận spam', slug: 'spam-comment-moderation', apiCategoryId: 'others' },
      { id: 'sub-customer-18', name: 'Cập nhật thông tin khách hàng', slug: 'customer-info-update', apiCategoryId: 'others' },
      { id: 'sub-customer-19', name: 'Phân loại khách hàng', slug: 'customer-segmentation', apiCategoryId: 'others' },
      { id: 'sub-customer-20', name: 'Theo dõi yêu cầu hỗ trợ', slug: 'ticket-tracking', apiCategoryId: 'others' },
    ],
  },
  {
    id: 'field-ai',
    name: 'AI & Tự động hóa',
    slug: 'ai-automation',
    icon: 'robot-outline',
    isHot: true,
    apiCategoryId: 'tech',
    subcategories: [
      { id: 'sub-ai-1', name: 'Viết prompt ChatGPT', slug: 'chatgpt-prompting', apiCategoryId: 'tech' },
      { id: 'sub-ai-2', name: 'Tối ưu prompt AI', slug: 'prompt-optimization', apiCategoryId: 'tech' },
      { id: 'sub-ai-3', name: 'Viết prompt tạo hình ảnh', slug: 'image-prompt-writing', apiCategoryId: 'tech' },
      { id: 'sub-ai-4', name: 'Tạo bộ prompt theo nhu cầu', slug: 'custom-prompts-pack', apiCategoryId: 'tech' },
      { id: 'sub-ai-5', name: 'Tạo nội dung bằng AI', slug: 'ai-content-generation', apiCategoryId: 'tech' },
      { id: 'sub-ai-6', name: 'Biên tập nội dung AI', slug: 'ai-content-editing', apiCategoryId: 'tech' },
      { id: 'sub-ai-7', name: 'Tóm tắt tài liệu bằng AI', slug: 'ai-doc-summarization', apiCategoryId: 'tech' },
      { id: 'sub-ai-8', name: 'Tạo hình ảnh bằng AI', slug: 'ai-image-generation', apiCategoryId: 'tech' },
      { id: 'sub-ai-9', name: 'Chỉnh sửa hình ảnh AI', slug: 'ai-image-editing', apiCategoryId: 'tech' },
      { id: 'sub-ai-10', name: 'Tạo chatbot FAQ', slug: 'faq-chatbot-setup', apiCategoryId: 'tech' },
      { id: 'sub-ai-11', name: 'Thiết lập chatbot website', slug: 'web-chatbot-setup', apiCategoryId: 'tech' },
      { id: 'sub-ai-12', name: 'Tạo chatbot chăm sóc khách hàng', slug: 'cs-chatbot-setup', apiCategoryId: 'tech' },
      { id: 'sub-ai-13', name: 'Tự động hóa Google Sheets', slug: 'google-sheets-automation', apiCategoryId: 'tech' },
      { id: 'sub-ai-14', name: 'Viết Google Apps Script', slug: 'apps-script-dev', apiCategoryId: 'tech' },
      { id: 'sub-ai-15', name: 'Tạo workflow bằng Make', slug: 'make-workflow', apiCategoryId: 'tech' },
      { id: 'sub-ai-16', name: 'Tạo workflow bằng Zapier', slug: 'zapier-workflow', apiCategoryId: 'tech' },
      { id: 'sub-ai-17', name: 'Tạo workflow bằng n8n', slug: 'n8n-workflow', apiCategoryId: 'tech' },
      { id: 'sub-ai-18', name: 'Tự động gửi email', slug: 'email-automation', apiCategoryId: 'tech' },
      { id: 'sub-ai-19', name: 'Tự động nhập dữ liệu', slug: 'data-entry-automation', apiCategoryId: 'tech' },
      { id: 'sub-ai-20', name: 'Tự động tạo báo cáo', slug: 'report-generation-automation', apiCategoryId: 'tech' },
      { id: 'sub-ai-21', name: 'Gắn nhãn dữ liệu', slug: 'data-labeling', apiCategoryId: 'tech' },
      { id: 'sub-ai-22', name: 'Phân loại dữ liệu', slug: 'data-sorting', apiCategoryId: 'tech' },
      { id: 'sub-ai-23', name: 'Kiểm tra nội dung do AI tạo', slug: 'ai-content-audit', apiCategoryId: 'tech' },
    ],
  },
];
