/**
 * Standardized API Error Codes
 */
const ERROR_CODES = {
  // Authentication & Session
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  FORBIDDEN: 'FORBIDDEN',
  
  // OTP & Verification
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_LOCKED: 'OTP_LOCKED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',

  // Request & Input Validation
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Wallet & Financial
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  ESCROW_NOT_FOUND: 'ESCROW_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',

  // System & Database
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE'
};

module.exports = ERROR_CODES;
